name: CI

on:
  release:
    types: [pull_request, push]

jobs:
  build_and_test_publish:
    runs-on: [small, amd64]

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - run: npm i
      - run: npm run build
      - run: npm test
